# Generated by ChatGPT on 2026-03-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foundation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("section_type", models.CharField(default="section", max_length=50)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                ("embed_html", models.TextField(blank=True)),
                ("button_text", models.CharField(blank=True, max_length=100)),
                ("button_url", models.URLField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="page_section_images", to="foundation.mediaasset")),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="foundation.page")),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
