# Generated by ChatGPT on 2026-03-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foundation", "0002_pagesection"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpcomingEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("date_label", models.CharField(blank=True, max_length=120)),
                ("location_label", models.CharField(blank=True, max_length=180)),
                ("cta_text", models.CharField(blank=True, max_length=100)),
                ("cta_url", models.URLField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("poster_image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="upcoming_event_posters", to="foundation.mediaasset")),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
