# Generated by Codex on 2026-03-26

from django.db import migrations
from django.utils import timezone


def create_default_pages(apps, schema_editor):
    Page = apps.get_model("foundation", "Page")
    now = timezone.now()
    defaults = [
        ("about", "About Us"),
        ("gallery", "Gallery"),
        ("news-stories", "Stories"),
        ("recent-projects", "Recent Projects"),
        ("awards", "Awards"),
        ("podcast", "Podcast"),
    ]

    for slug, title in defaults:
        Page.objects.get_or_create(
            slug=slug,
            defaults={
                "title": title,
                "status": "published",
                "publish_at": now,
                "body": "",
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("foundation", "0003_upcomingevent"),
    ]

    operations = [
        migrations.RunPython(create_default_pages, migrations.RunPython.noop),
    ]
