# Generated by Codex on 2026-03-26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("foundation", "0004_seed_default_pages"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="gallery_items", to="foundation.mediaasset")),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")], default="draft", max_length=20)),
                ("publish_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("seo_description", models.TextField(blank=True)),
                ("canonical_url", models.URLField(blank=True)),
                ("og_title", models.CharField(blank=True, max_length=255)),
                ("og_description", models.TextField(blank=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("excerpt", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("date_label", models.CharField(blank=True, max_length=120)),
                ("location_label", models.CharField(blank=True, max_length=180)),
                ("read_time", models.CharField(blank=True, max_length=50)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("is_featured", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("featured_image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="story_images", to="foundation.mediaasset")),
                ("og_image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="foundation.mediaasset")),
            ],
            options={
                "ordering": ["sort_order", "-publish_at"],
            },
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("presenter", models.CharField(blank=True, max_length=255)),
                ("year", models.CharField(blank=True, max_length=20)),
                ("summary", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="award_images", to="foundation.mediaasset")),
                ("detail_images", models.ManyToManyField(blank=True, related_name="award_detail_images", to="foundation.mediaasset")),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PodcastEpisode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")], default="draft", max_length=20)),
                ("publish_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("duration_label", models.CharField(blank=True, max_length=50)),
                ("host", models.CharField(blank=True, max_length=255)),
                ("audio_url", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("cover_image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="podcast_cover_images", to="foundation.mediaasset")),
            ],
            options={
                "ordering": ["sort_order", "-publish_at"],
            },
        ),
    ]
